export type Screen = 'home' | 'lessons' | 'exercises' | 'assistant' | 'profile' | 'community' | 'quick-review' | 'exam' | 'leaderboard' | 'past-exams' | 'exam-generator' | 'study-plan';

export interface UserProfile {
  id: string;
  name: string;
  avatarUrl: string;
  points: number;
  streak: number;
  badges: Badge[];
  stream: string;
}

export interface LeaderboardUser {
    id: string;
    name: string;
    avatarUrl: string;
    score: number;
    rank: number;
}

export interface Badge {
  id: string;
  name: string;
  icon: string; // Emoji or component name
  description: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string; // Emoji
  color: string;
  lessons: Lesson[];
}

export interface QuizOption {
  text: string;
  is_correct: boolean;
}

export interface QuizQuestion {
    question: string;
    options: QuizOption[];
}

export interface Lesson {
  id: string;
  title: string;
  summary: string;
  content: string;
  examples: string[];
  completed: boolean;
  difficulty: 'easy' | 'medium' | 'hard';
  imageUrl?: string;
  videoUrl?: string;
  pdfUrl?: string;
  audioUrl?: string; // For text-to-speech
  quiz?: QuizQuestion[];
  subjectId: string; // Added to easily track progress
}

export interface Exercise {
  id: string;
  subject: string;
  type: 'mcq' | 'true-false';
  question: string;
  options: QuizOption[];
}

export interface Flashcard {
    id: string;
    subject: string;
    term: string;
    definition: string;
}

export interface ChatMessage {
    role: 'user' | 'model';
    parts: ({ text: string } | { inlineData: { mimeType: string; data: string } })[];
    isLoading?: boolean;
}

export interface PastExam {
  id: string;
  subjectId: string;
  subjectName: string;
  year: number;
  topicUrl: string;
  solutionUrl: string;
}

export interface CommunityAnswer {
    id: string;
    author: string;
    avatarUrl: string;
    text: string;
    timestamp: string;
}

export interface CommunityPost {
    id: string;
    author: string;
    avatarUrl: string;
    question: string;
    subject: string;
    timestamp: string;
    answers: CommunityAnswer[];
}

export interface RealtimeChatMessage {
    id: number;
    createdAt: string;
    userName: string;
    avatarUrl: string;
    content: string;
    imageUrl?: string;
}

export interface Challenge {
  id: string;
  title: string;
  description: string;
  subject_id: string;
  question_count: number;
  time_limit_seconds: number;
}

export interface ChallengeLobby {
  id: string; // UUID
  challenge_id: string;
  status: 'waiting' | 'running' | 'finished';
  created_at: string;
  host_username: string;
}

export interface ChallengeParticipant {
  user_name: string;
  avatar_url: string;
  score: number;
  finish_time_seconds?: number;
}


// --- SUPABASE TYPES ---
// This would typically be generated by `supabase gen types typescript`
// I'm creating it manually based on the SQL schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      answers: {
        Row: {
          author: string
          avatar_url: string | null
          created_at: string | null
          id: string
          post_id: string | null
          text: string
          user_id: string | null
        }
        Insert: {
          author: string
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          post_id?: string | null
          text: string
          user_id?: string | null
        }
        Update: {
          author?: string
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          post_id?: string | null
          text?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "answers_post_id_fkey"
            columns: ["post_id"]
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "answers_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      badges: {
        Row: {
          description: string
          icon: string | null
          id: string
          name: string
        }
        Insert: {
          description: string
          icon?: string | null
          id: string
          name: string
        }
        Update: {
          description?: string
          icon?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      chat_messages: {
        Row: {
          id: number
          created_at: string | null
          user_name: string
          avatar_url: string | null
          content: string
          image_url?: string | null
        }
        Insert: {
          id?: number
          created_at?: string | null
          user_name: string
          avatar_url?: string | null
          content: string
          image_url?: string | null
        }
        Update: {
          id?: number
          created_at?: string | null
          user_name?: string
          avatar_url?: string | null
          content?: string
          image_url?: string | null
        }
        Relationships: []
      }
      challenges: {
        Row: {
          id: string
          title: string
          description: string | null
          subject_id: string | null
          question_count: number
          time_limit_seconds: number
        }
        Insert: {
          id: string
          title: string
          description?: string | null
          subject_id?: string | null
          question_count?: number
          time_limit_seconds?: number
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          subject_id?: string | null
          question_count?: number
          time_limit_seconds?: number
        }
        Relationships: [
          {
            foreignKeyName: "challenges_subject_id_fkey"
            columns: ["subject_id"]
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      challenge_lobbies: {
        Row: {
          id: string
          challenge_id: string
          status: string
          created_at: string
          host_username: string | null
        }
        Insert: {
          id?: string
          challenge_id: string
          status?: string
          created_at?: string
          host_username?: string | null
        }
        Update: {
          id?: string
          challenge_id?: string
          status?: string
          created_at?: string
          host_username?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "challenge_lobbies_challenge_id_fkey"
            columns: ["challenge_id"]
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          }
        ]
      }
      challenge_participants: {
        Row: {
          id: number
          lobby_id: string
          user_name: string
          score: number
          finish_time_seconds: number | null
        }
        Insert: {
          id?: number
          lobby_id: string
          user_name: string
          score?: number
          finish_time_seconds?: number | null
        }
        Update: {
          id?: number
          lobby_id?: string
          user_name?: string
          score?: number
          finish_time_seconds?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "challenge_participants_lobby_id_fkey"
            columns: ["lobby_id"]
            referencedRelation: "challenge_lobbies"
            referencedColumns: ["id"]
          }
        ]
      }
      exercises: {
        Row: {
          correct_answer: string
          id: string
          options: Json | null // This is more robust; can be string[] or object[]
          question: string
          subject: string
          type: string
        }
        Insert: {
          correct_answer: string
          id: string
          options?: Json | null
          question: string
          subject: string
          type: string
        }
        Update: {
          correct_answer?: string
          id?: string
          options?: Json | null
          question?: string
          subject?: string
          type?: string
        }
        Relationships: []
      }
      flashcards: {
        Row: {
          definition: string
          id: string
          subject: string
          term: string
        }
        Insert: {
          definition: string
          id: string
          subject: string
          term: string
        }
        Update: {
          definition?: string
          id?: string
          subject?: string
          term?: string
        }
        Relationships: []
      }
      lessons: {
        Row: {
          audio_url: string | null
          completed: boolean | null
          content: string | null
          difficulty: string | null
          examples: string[] | null
          id: string
          image_url: string | null
          pdf_url: string | null
          quiz: Json | null
          subject_id: string | null
          summary: string | null
          title: string
          video_url: string | null
        }
        Insert: {
          audio_url?: string | null
          completed?: boolean | null
          content?: string | null
          difficulty?: string | null
          examples?: string[] | null
          id: string
          image_url?: string | null
          pdf_url?: string | null
          quiz?: Json | null
          subject_id?: string | null
          summary?: string | null
          title: string
          video_url?: string | null
        }
        Update: {
          audio_url?: string | null
          completed?: boolean | null
          content?: string | null
          difficulty?: string | null
          examples?: string[] | null
          id?: string
          image_url?: string | null
          pdf_url?: string | null
          quiz?: Json | null
          subject_id?: string | null
          summary?: string | null
          title?: string
          video_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lessons_subject_id_fkey"
            columns: ["subject_id"]
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      past_exams: {
        Row: {
          id: string
          solution_url: string | null
          subject_id: string | null
          subject_name: string
          topic_url: string | null
          year: number
        }
        Insert: {
          id: string
          solution_url?: string | null
          subject_id?: string | null
          subject_name: string
          topic_url?: string | null
          year: number
        }
        Update: {
          id?: string
          solution_url?: string | null
          subject_id?: string | null
          subject_name?: string
          topic_url?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "past_exams_subject_id_fkey"
            columns: ["subject_id"]
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      posts: {
        Row: {
          author: string
          avatar_url: string | null
          created_at: string
          id: string
          question: string
          subject: string | null
          user_id: string | null
        }
        Insert: {
          author: string
          avatar_url?: string | null
          created_at?: string
          id?: string
          question: string
          subject?: string | null
          user_id?: string | null
        }
        Update: {
          author?: string
          avatar_url?: string | null
          created_at?: string
          id?: string
          question?: string
          subject?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "posts_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          id: string
          name: string
          points: number | null
          streak: number | null
          stream: string | null
        }
        Insert: {
          avatar_url?: string | null
          id?: string
          name: string
          points?: number | null
          streak?: number | null
          stream?: string | null
        }
        Update: {
          avatar_url?: string | null
          id?: string
          name?: string
          points?: number | null
          streak?: number | null
          stream?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      subjects: {
        Row: {
          color: string | null
          icon: string | null
          id: string
          name: string
        }
        Insert: {
          color?: string | null
          icon?: string | null
          id: string
          name: string
        }
        Update: {
          color?: string | null
          icon?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      user_badges: {
        Row: {
          awarded_at: string | null
          badge_id: string
          id: number
          user_name: string
        }
        Insert: {
          awarded_at?: string | null
          badge_id: string
          id?: number
          user_name: string
        }
        Update: {
          awarded_at?: string | null
          badge_id?: string
          id?: number
          user_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_badge_id_fkey"
            columns: ["badge_id"]
            referencedRelation: "badges"
            referencedColumns: ["id"]
          }
        ]
      }
      user_lesson_progress: {
        Row: {
          created_at: string | null
          id: number
          lesson_id: string
          user_name: string
        }
        Insert: {
          created_at?: string | null
          id?: number
          lesson_id: string
          user_name: string
        }
        Update: {
          created_at?: string | null
          id?: number
          lesson_id?: string
          user_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_lesson_progress_lesson_id_fkey"
            columns: ["lesson_id"]
            referencedRelation: "lessons"
            referencedColumns: ["id"]
          }
        ]
      }
      user_stats: {
        Row: {
          avatar_url: string | null
          last_active_date: string | null
          points: number
          stream: string | null
          streak: number
          user_name: string
        }
        Insert: {
          avatar_url?: string | null
          last_active_date?: string | null
          points?: number
          stream?: string | null
          streak?: number
          user_name: string
        }
        Update: {
          avatar_url?: string | null
          last_active_date?: string | null
          points?: number
          stream?: string | null
          streak?: number
          user_name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
