export type Screen = 'home' | 'lessons' | 'exercises' | 'assistant' | 'profile' | 'community' | 'quick-review' | 'exam' | 'leaderboard' | 'past-exams' | 'exam-generator' | 'study-plan';

export interface UserProfile {
  id: string;
  name: string;
  avatarUrl: string;
  points: number;
  streak: number;
  badges: Badge[];
}

export interface LeaderboardUser {
    id: string;
    name: string;
    avatarUrl: string;
    score: number;
    rank: number;
}

export interface Badge {
  id: string;
  name: string;
  icon: string; // Emoji or component name
  description: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string; // Emoji
  color: string;
  lessons: Lesson[];
}

export interface QuizQuestion {
    question: string;
    options: string[];
    correctAnswer: string;
}

export interface Lesson {
  id: string;
  title: string;
  summary: string;
  content: string;
  examples: string[];
  completed: boolean;
  difficulty: 'easy' | 'medium' | 'hard';
  imageUrl?: string;
  videoUrl?: string;
  pdfUrl?: string;
  audioUrl?: string; // For text-to-speech
  quiz?: QuizQuestion[];
}

export interface Exercise {
  id: string;
  subject: string;
  type: 'mcq' | 'true-false';
  question: string;
  options?: string[]; // only for mcq
  correctAnswer: string; // "True", "False", or the correct option string
}

export interface Flashcard {
    id: string;
    subject: string;
    term: string;
    definition: string;
}

export interface ChatMessage {
    role: 'user' | 'model';
    parts: ({ text: string } | { inlineData: { mimeType: string; data: string } })[];
    isLoading?: boolean;
}

export interface PastExam {
  id: string;
  subjectId: string;
  subjectName: string;
  year: number;
  topicUrl: string;
  solutionUrl: string;
}

export interface CommunityAnswer {
    id: string;
    author: string;
    avatarUrl: string;
    text: string;
    timestamp: string;
}

export interface CommunityPost {
    id: string;
    author: string;
    avatarUrl: string;
    question: string;
    subject: string;
    timestamp: string;
    answers: CommunityAnswer[];
}


// --- SUPABASE TYPES ---
// This would typically be generated by `supabase gen types typescript`
// I'm creating it manually based on the SQL schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      answers: {
        Row: {
          author: string
          avatar_url: string | null
          created_at: string | null
          id: string
          post_id: string | null
          text: string
        }
        Insert: {
          author: string
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          post_id?: string | null
          text: string
        }
        Update: {
          author?: string
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          post_id?: string | null
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "answers_post_id_fkey"
            columns: ["post_id"]
            referencedRelation: "posts"
            referencedColumns: ["id"]
          }
        ]
      }
      badges: {
        Row: {
          description: string
          icon: string | null
          id: string
          name: string
          profile_id: string | null
        }
        Insert: {
          description: string
          icon?: string | null
          id: string
          name: string
          profile_id?: string | null
        }
        Update: {
          description?: string
          icon?: string | null
          id?: string
          name?: string
          profile_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "badges_profile_id_fkey"
            columns: ["profile_id"]
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      exercises: {
        Row: {
          correct_answer: string
          id: string
          options: string[] | null
          question: string
          subject: string
          type: string
        }
        Insert: {
          correct_answer: string
          id: string
          options?: string[] | null
          question: string
          subject: string
          type: string
        }
        Update: {
          correct_answer?: string
          id?: string
          options?: string[] | null
          question?: string
          subject?: string
          type?: string
        }
        Relationships: []
      }
      flashcards: {
        Row: {
          definition: string
          id: string
          subject: string
          term: string
        }
        Insert: {
          definition: string
          id: string
          subject: string
          term: string
        }
        Update: {
          definition?: string
          id?: string
          subject?: string
          term?: string
        }
        Relationships: []
      }
      lessons: {
        Row: {
          audio_url: string | null
          completed: boolean | null
          content: string | null
          difficulty: string | null
          examples: string[] | null
          id: string
          image_url: string | null
          pdf_url: string | null
          quiz: Json | null
          subject_id: string | null
          summary: string | null
          title: string
          video_url: string | null
        }
        Insert: {
          audio_url?: string | null
          completed?: boolean | null
          content?: string | null
          difficulty?: string | null
          examples?: string[] | null
          id: string
          image_url?: string | null
          pdf_url?: string | null
          quiz?: Json | null
          subject_id?: string | null
          summary?: string | null
          title: string
          video_url?: string | null
        }
        Update: {
          audio_url?: string | null
          completed?: boolean | null
          content?: string | null
          difficulty?: string | null
          examples?: string[] | null
          id?: string
          image_url?: string | null
          pdf_url?: string | null
          quiz?: Json | null
          subject_id?: string | null
          summary?: string | null
          title?: string
          video_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lessons_subject_id_fkey"
            columns: ["subject_id"]
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      past_exams: {
        Row: {
          id: string
          solution_url: string | null
          subject_id: string | null
          subject_name: string
          topic_url: string | null
          year: number
        }
        Insert: {
          id: string
          solution_url?: string | null
          subject_id?: string | null
          subject_name: string
          topic_url?: string | null
          year: number
        }
        Update: {
          id?: string
          solution_url?: string | null
          subject_id?: string | null
          subject_name?: string
          topic_url?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "past_exams_subject_id_fkey"
            columns: ["subject_id"]
            referencedRelation: "subjects"
            referencedColumns: ["id"]
          }
        ]
      }
      posts: {
        Row: {
          author: string
          avatar_url: string | null
          created_at: string
          id: string
          question: string
          subject: string | null
        }
        Insert: {
          author: string
          avatar_url?: string | null
          created_at?: string
          id?: string
          question: string
          subject?: string | null
        }
        Update: {
          author?: string
          avatar_url?: string | null
          created_at?: string
          id?: string
          question?: string
          subject?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          id: string
          name: string
          points: number | null
          streak: number | null
        }
        Insert: {
          avatar_url?: string | null
          id?: string
          name: string
          points?: number | null
          streak?: number | null
        }
        Update: {
          avatar_url?: string | null
          id?: string
          name?: string
          points?: number | null
          streak?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      subjects: {
        Row: {
          color: string | null
          icon: string | null
          id: string
          name: string
        }
        Insert: {
          color?: string | null
          icon?: string | null
          id: string
          name: string
        }
        Update: {
          color?: string | null
          icon?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}